No more bug!
CallStack (from HasCallStack):
  error, called at t11715.hs:15:31 in main:Main
